import { InvoiceWithDetails } from '@/modules/invoicing/schema'
import { Contact } from '@/modules/clients/server/repository'

// Obviously-fake data for the template editor's live preview only — never
// persisted, never a real invoice. Lets a tenant see the effect of a layout
// change without needing a real invoice to test against.
export const SAMPLE_INVOICE_FOR_PREVIEW: InvoiceWithDetails = {
  id: 'sample-invoice-id',
  tenant_id: 'sample-tenant-id',
  job_id: null,
  contact_id: 'sample-contact-id',
  brand_id: 'sample-brand-id',
  brand_snapshot: null,
  invoice_number: 'INV-00042',
  status: 'sent',
  subtotal: 850,
  tax_amount: 170,
  total: 1020,
  issued_at: '2026-01-15',
  due_date: '2026-01-29',
  paid_at: null,
  notes: null,
  created_at: '2026-01-15T09:00:00Z',
  updated_at: null,
  lineItems: [
    {
      id: 'sample-line-1',
      tenant_id: 'sample-tenant-id',
      invoice_id: 'sample-invoice-id',
      description: 'Removals service — 3 bedroom house',
      quantity: 1,
      unit_price: 650,
      amount: 650,
      sort_order: 0,
      created_at: '2026-01-15T09:00:00Z',
    },
    {
      id: 'sample-line-2',
      tenant_id: 'sample-tenant-id',
      invoice_id: 'sample-invoice-id',
      description: 'Packing materials',
      quantity: 1,
      unit_price: 120,
      amount: 120,
      sort_order: 1,
      created_at: '2026-01-15T09:00:00Z',
    },
    {
      id: 'sample-line-3',
      tenant_id: 'sample-tenant-id',
      invoice_id: 'sample-invoice-id',
      description: 'Stairs surcharge',
      quantity: 2,
      unit_price: 40,
      amount: 80,
      sort_order: 2,
      created_at: '2026-01-15T09:00:00Z',
    },
  ],
  schedules: [
    {
      id: 'sample-schedule-1',
      tenant_id: 'sample-tenant-id',
      invoice_id: 'sample-invoice-id',
      description: 'Balance Due',
      amount: 1020,
      due_date: '2026-01-29',
      status: 'pending',
      created_at: '2026-01-15T09:00:00Z',
      updated_at: null,
    },
  ],
  payments: [
    {
      id: 'sample-payment-1',
      tenant_id: 'sample-tenant-id',
      invoice_id: 'sample-invoice-id',
      payment_schedule_id: null,
      amount: 200,
      method: 'card',
      stripe_payment_intent_id: null,
      status: 'succeeded',
      paid_at: '2026-01-10T09:00:00Z',
      created_at: '2026-01-10T09:00:00Z',
    },
  ],
  job: {
    status: 'scheduled',
    move_date: '2026-01-20',
    customer_notes: 'Sofa needs disassembly. Parking permit required on destination street.',
    origin_address: {
      line_1: '12 Sample Street',
      line_2: null,
      city: 'London',
      county: null,
      postcode: 'E1 6AN',
      country: 'GB',
    },
    destination_address: {
      line_1: '48 Example Road',
      line_2: 'Flat 2',
      city: 'Manchester',
      county: null,
      postcode: 'M1 4BT',
      country: 'GB',
    },
  },
}

export const SAMPLE_CONTACT_FOR_PREVIEW: Contact = {
  id: 'sample-contact-id',
  tenant_id: 'sample-tenant-id',
  type: 'residential',
  user_id: null,
  first_name: 'Jordan',
  last_name: 'Sample',
  company_name: null,
  email: 'jordan.sample@example.com',
  phone: '07700 900000',
  alt_phone: null,
  notes: null,
  is_archived: false,
  created_by: null,
  updated_by: null,
  stripe_customer_id: null,
  default_payment_method_id: null,
  created_at: '2026-01-01T00:00:00Z',
  updated_at: null,
} as unknown as Contact
