import { SupabaseClient } from '@supabase/supabase-js'
import { Database } from '@/types/database.types'
import { isWorkflowModuleEnabled } from './repository'

type WorkflowAction = Database['public']['Tables']['automation_workflow_actions']['Row']
type Workflow = Database['public']['Tables']['automation_workflows']['Row'] & {
  automation_workflow_actions: WorkflowAction[]
}

/**
 * Synchronously executes all matching active workflows for a given domain event.
 *
 * CRITICAL DESIGN REQUIREMENT: This function must NEVER throw an exception back to
 * the caller. It runs inline during core actions (e.g., lead creation). If a
 * workflow fails, we log it and move on. We must never drop a real customer lead
 * just because an automated rule was misconfigured.
 */
export async function executeWorkflows(
  supabase: SupabaseClient<Database>,
  eventType: Database['public']['Enums']['workflow_trigger_event_type'],
  payload: Record<string, any>,
  eventId: string,
  explicitTenantId?: string
) {
  try {
    // 1. Resolve tenant_id. If not passed explicitly, the current authenticated
    // user's JWT will naturally scope all queries via RLS. However, to bypass RLS
    // or properly log execution with service-role, an explicit tenantId is required
    // if available.
    let tenantId = explicitTenantId
    if (!tenantId) {
      const { data: { user } } = await supabase.auth.getUser()
      tenantId = user?.app_metadata?.tenant_id
      if (!tenantId) {
        console.warn(`[Workflow Engine] Could not resolve tenant_id for event ${eventType} (${eventId}). Skipping workflows.`)
        return
      }
    }

    // 2. Fast-fail if the tenant isn't entitled to use workflows
    const isEnabled = await isWorkflowModuleEnabled(supabase, tenantId)
    if (!isEnabled) {
      return
    }

    // 3. Fetch active workflows for this event type
    const { data: activeWorkflows, error: fetchErr } = await supabase
      .from('automation_workflows')
      .select('*, automation_workflow_actions(*)')
      .eq('tenant_id', tenantId)
      .eq('is_active', true)
      .eq('trigger_event_type', eventType)
      .order('sort_order', { referencedTable: 'automation_workflow_actions', ascending: true })

    if (fetchErr) {
      console.error(`[Workflow Engine] Failed to fetch workflows for event ${eventId}:`, fetchErr)
      return
    }

    if (!activeWorkflows || activeWorkflows.length === 0) {
      return
    }

    // 4. Evaluate each workflow and run actions if conditions match
    for (const workflow of activeWorkflows as unknown as Workflow[]) {
      // Flat JSON equality check for conditions
      const conditions = workflow.trigger_conditions as Record<string, any>
      let match = true
      for (const [key, expectedValue] of Object.entries(conditions)) {
        if (payload[key] !== expectedValue) {
          match = false
          break
        }
      }

      if (!match) {
        continue // Skip this workflow
      }

      // We have a match! Insert execution log
      const { data: logRow, error: logErr } = await supabase
        .from('automation_workflow_execution_log')
        .insert({
          tenant_id: tenantId,
          workflow_id: workflow.id,
          event_id: eventId,
          status: 'pending',
          logs: []
        })
        .select('id')
        .single()

      if (logErr || !logRow) {
        console.error(`[Workflow Engine] Failed to create execution log for workflow ${workflow.id}:`, logErr)
        continue // Skip to next workflow, we can't track this one
      }

      const executionLogId = logRow.id
      let successCount = 0
      let failedCount = 0
      const actionLogs: Array<{ action_id: string; type: string; status: 'success' | 'failed'; error?: string }> = []

      // Run each action
      for (const action of workflow.automation_workflow_actions || []) {
        try {
          const config = action.action_config as Record<string, any>
          
          if (action.action_type === 'create_task') {
            const { createTask } = await import('@/modules/tasks/server/repository')
            const result = await createTask(supabase, tenantId, {
              title: config.title || 'Automated Task',
              description: `Generated by workflow: ${workflow.name}`,
              status: 'pending',
              due_date: new Date(Date.now() + 86400000 * 3).toISOString(), // default +3 days
              lead_id: payload.lead_id,
              contact_id: payload.contact_id
            })
            if (result.error) {
              throw new Error(result.error.message || JSON.stringify(result.error))
            }

          } else if (action.action_type === 'update_lead_stage') {
            const leadId = payload.lead_id
            if (!leadId) throw new Error('No lead_id provided in event payload')
            
            const { error: updateErr } = await supabase
              .from('leads')
              .update({ stage: config.stage })
              .eq('tenant_id', tenantId)
              .eq('id', leadId)
              
            if (updateErr) throw updateErr
          } else {
            throw new Error(`Unsupported action type: ${action.action_type}`)
          }

          successCount++
          actionLogs.push({ action_id: action.id, type: action.action_type, status: 'success' })
        } catch (err: any) {
          failedCount++
          actionLogs.push({ action_id: action.id, type: action.action_type, status: 'failed', error: err.message })
        }
      }

      // Determine final status
      let finalStatus: 'success' | 'failed' | 'partial' = 'success'
      if (failedCount > 0) {
        finalStatus = successCount === 0 ? 'failed' : 'partial'
      }

      // Update log
      await supabase
        .from('automation_workflow_execution_log')
        .update({
          status: finalStatus,
          logs: actionLogs as any
        })
        .eq('id', executionLogId)
    }

  } catch (err: any) {
    // Ultimate safety net: never throw back to the caller
    console.error(`[Workflow Engine] Fatal error during workflow execution for event ${eventId}:`, err)
  }
}
